jobs:
# Give each job a unique name. The name will be displayed in the Fivetran dashboard once your jobs are imported.
#  - name: daily
#    schedule: 0 12 * * * # Define when this job should run, using cron format. This example will run every day at 12:00pm (according to your warehouse timezone). For help with cron formatting, visit https://crontab.guru/.
#    steps:
#      - name: run models # Give each step in your job a name. This will enable you to track the steps in the logs.
#        command: dbt run # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
#      - name: test models
#        command: dbt test # This example will run all your tests.


 - name: weekdays
   schedule: 30 7 * * 1-5 # The example will run every weekday at 7:30am.
   steps:
#      - name: install dependencies
#        command: "dbt deps --vars \"
#                     {'SNOWFLAKE_PREP_DATABASE': 'PREP', 
#                      'SNOWFLAKE_PROD_DATABASE': 'PROD', 
#                      'SNOWFLAKE_TRANSFORM_WAREHOUSE': 'TRANSFORMING', 
#                      'SNOWFLAKE_SNAPSHOT_DATABASE': 'RAW'
#                     }\""
#      - name: run snapshots
#        command: "dbt snapshot --select tag:nightly --vars \"
#                     {'SNOWFLAKE_PREP_DATABASE': 'PREP', 
#                      'SNOWFLAKE_PROD_DATABASE': 'PROD', 
#                      'SNOWFLAKE_TRANSFORM_WAREHOUSE': 'TRANSFORMING', 
#                      'SNOWFLAKE_SNAPSHOT_DATABASE': 'RAW'
#                     }\""
     - name: run models
       command: "dbt run --vars \"{'key1':'value', 'key2':'value2'}\""
#        command: "FOO=sample BAR=example dbt run --vars \"{'key1':'value', 'key2':'value2'}\""
#      - name: goofy command
#        command: "dbt 
#                    run-operation fivetran_utils.generate_columns_macro 
#                    --args '{\"table_name\": \"ACCOUNT_DATA\", 
#                             \"schema_name\": \"DBT_TRANSFORMATIONS\", 
#                             \"database_name\": \"dbt-package-testing\"}'"
